package by.htp.libsite.controller;
//utf-8
public enum CommandName {
	SIGN_IN, SEARCH_BOOK_TITLE, CHECK_IN, PASSWORD_RECOVERY, ERROR, REGISTRATION_PAGE, RECOVERY_PAGE,
	SIGN_OUT, SEARCH_BOOK_AUTHOR, SEARCH_BOOK_GENRE, READ_BOOK, SEARCH_BOOK_USER_ID, DELETE_BOOK,
	CHANGE_BOOK_CONTENT, ADDING_PAGE, ADD_BOOK, GET_ALL_USER, PROFILE_PAGE, GOOD_ADD_BOOK
}
